ejs:
    template: "./template/default.ejs"
    marked:
        renderer: "./renderer/defaultRenderer.js"
        ejsKey: "content"
    include:
        file: 
            uikitmincss: "custom/my.uikit.css"
